/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTenantsTenantIdUsersIndexRouteImport } from './routes/_authenticated/tenants.$tenantId.users/index'
import { Route as AuthenticatedTenantsTenantIdUsersUserIdRouteImport } from './routes/_authenticated/tenants.$tenantId.users/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsTenantIdUsersIndexRoute =
  AuthenticatedTenantsTenantIdUsersIndexRouteImport.update({
    id: '/tenants/$tenantId/users/',
    path: '/tenants/$tenantId/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdUsersUserIdRoute =
  AuthenticatedTenantsTenantIdUsersUserIdRouteImport.update({
    id: '/tenants/$tenantId/users/$userId',
    path: '/tenants/$tenantId/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/tenants/$tenantId/users/$userId': typeof AuthenticatedTenantsTenantIdUsersUserIdRoute
  '/tenants/$tenantId/users/': typeof AuthenticatedTenantsTenantIdUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/tenants/$tenantId/users/$userId': typeof AuthenticatedTenantsTenantIdUsersUserIdRoute
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tenants/$tenantId/users/$userId': typeof AuthenticatedTenantsTenantIdUsersUserIdRoute
  '/_authenticated/tenants/$tenantId/users/': typeof AuthenticatedTenantsTenantIdUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tenants/$tenantId/users/$userId'
    | '/tenants/$tenantId/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/tenants/$tenantId/users/$userId'
    | '/tenants/$tenantId/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/tenants/$tenantId/users/$userId'
    | '/_authenticated/tenants/$tenantId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/users/': {
      id: '/_authenticated/tenants/$tenantId/users/'
      path: '/tenants/$tenantId/users'
      fullPath: '/tenants/$tenantId/users/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/users/$userId': {
      id: '/_authenticated/tenants/$tenantId/users/$userId'
      path: '/tenants/$tenantId/users/$userId'
      fullPath: '/tenants/$tenantId/users/$userId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTenantsTenantIdUsersUserIdRoute: typeof AuthenticatedTenantsTenantIdUsersUserIdRoute
  AuthenticatedTenantsTenantIdUsersIndexRoute: typeof AuthenticatedTenantsTenantIdUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTenantsTenantIdUsersUserIdRoute:
    AuthenticatedTenantsTenantIdUsersUserIdRoute,
  AuthenticatedTenantsTenantIdUsersIndexRoute:
    AuthenticatedTenantsTenantIdUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
