/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTenantsTenantIdCompaniesIndexRouteImport } from './routes/_authenticated/tenants.$tenantId.companies/index'
import { Route as AuthenticatedTenantsTenantIdCompaniesCompanyIdRouteImport } from './routes/_authenticated/tenants.$tenantId.companies/$companyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsTenantIdCompaniesIndexRoute =
  AuthenticatedTenantsTenantIdCompaniesIndexRouteImport.update({
    id: '/tenants/$tenantId/companies/',
    path: '/tenants/$tenantId/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute =
  AuthenticatedTenantsTenantIdCompaniesCompanyIdRouteImport.update({
    id: '/tenants/$tenantId/companies/$companyId',
    path: '/tenants/$tenantId/companies/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/tenants/$tenantId/companies/$companyId': typeof AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute
  '/tenants/$tenantId/companies/': typeof AuthenticatedTenantsTenantIdCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/tenants/$tenantId/companies/$companyId': typeof AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute
  '/tenants/$tenantId/companies': typeof AuthenticatedTenantsTenantIdCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tenants/$tenantId/companies/$companyId': typeof AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute
  '/_authenticated/tenants/$tenantId/companies/': typeof AuthenticatedTenantsTenantIdCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tenants/$tenantId/companies/$companyId'
    | '/tenants/$tenantId/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/tenants/$tenantId/companies/$companyId'
    | '/tenants/$tenantId/companies'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/tenants/$tenantId/companies/$companyId'
    | '/_authenticated/tenants/$tenantId/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/companies/': {
      id: '/_authenticated/tenants/$tenantId/companies/'
      path: '/tenants/$tenantId/companies'
      fullPath: '/tenants/$tenantId/companies/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/companies/$companyId': {
      id: '/_authenticated/tenants/$tenantId/companies/$companyId'
      path: '/tenants/$tenantId/companies/$companyId'
      fullPath: '/tenants/$tenantId/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute: typeof AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute
  AuthenticatedTenantsTenantIdCompaniesIndexRoute: typeof AuthenticatedTenantsTenantIdCompaniesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute:
    AuthenticatedTenantsTenantIdCompaniesCompanyIdRoute,
  AuthenticatedTenantsTenantIdCompaniesIndexRoute:
    AuthenticatedTenantsTenantIdCompaniesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
